name: chef_connect_india
description: hire your chef.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  adobe_xd: ^2.0.1
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  cloud_firestore: ^3.1.10
  country_code_picker: ^2.0.2
  cupertino_icons: ^1.0.2
  custom_radio_grouped_button: any
  dots_indicator: ^2.0.0
  firebase_auth: ^3.3.10
  firebase_storage: ^10.2.9
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.1.5
  flutter_neumorphic: ^3.2.0
  flutter_rating_bar: ^4.0.0
  flutter_riverpod: ^1.0.3
  flutter_secure_storage: ^5.0.2
  flutter_secure_storage_web: ^1.0.2
  flutter_speed_dial: ^5.1.0
  flutter_spinkit: ^5.1.0
  flutter_svg: null
  fluttertoast: ^8.0.9
  getwidget: ^2.0.5
  glassmorphism: ^3.0.0
  google_fonts: ^2.3.1
  image_picker: ^0.8.4+11
  multi_select_flutter: ^4.1.2
  multiselect_formfield: ^0.1.7
  onboarding: ^3.0.0
  otp_text_field: ^1.1.2
  paginate_firestore: ^1.0.3
  pin_code_fields: ^7.3.0
  pinput: ^2.1.4
  provider: ^6.0.2
  rflutter_alert: ^2.0.4
  shared_preferences: ^2.0.13
  smooth_star_rating_nsafe: ^1.0.0+1
  # cached_network_image:

flutter_native_splash:
  color: "#03203C"
  image: assets/logo_cci.png

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo_cci_foreground.png"
  adaptive_icon_foreground: "assets/logo_cci_foreground.png"
  adaptive_icon_background: "#000000"
# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/Chef connect logo.png"
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/socialicons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-ExtraBold.ttf
          weight: 800
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
